### ISSUE TITLE
popToRootViewControllerAnimated is wrong

### ISSUE THREAD

**Issue by vojtaBelovsky** [bfolder/BFNavigationController#4]
method -(NSArray *)popToRootViewControllerAnimated: (BOOL)animated has theese issues:

1) It returns only n-1 controllers ( I don't count that one, which remains as root view controller )
2) First issue cause that for that one view controller that is not returned is not called method `removeFromParentViewController`
3) Returned view controllers are not returned in order that is should be returned ( it should be returned in order like if you pop every single controller, now it's in order it was added to navgiation controller )

cheers

**Comment by bfolder** [comment]
Hey,
yes, you are right. The issues seem to have been introduced in the last PR. They should be fixed here a1fb08b00b925dc56471a7ece4e6bbe8988833e3

Heiko

**Comment by vojtaBelovsky** [comment]
cool!
